### ISSUE TITLE
[Emails] Warn users about not using PGP

### ISSUE THREAD

**Issue by jholdstock** [degeri/Decred-Bug-Bounty-Proposal#7]
If we receive a non-encrypted email, mention that PGP should be used. Also update payout templates to notify that payout has been reduced due to not encrypting

**Comment by degeri** [comment]
Jumped the gun on this . https://github.com/degeri/Decred-Bug-Bounty-Proposal/blob/master/2019/email-templates/1-report-received.txt  . should have run it by you first

**Comment by jholdstock** [comment]
OK - lets keep this open then for the second part - notify a reporter that their payout has been reduced due to not encrypting

**Comment by degeri** [comment]
Addressed here https://github.com/degeri/Decred-Bug-Bounty-Proposal/blob/master/2019/email-templates/5-request-payment-details.txt#L5
